Repository openshift/osdctl, pull requests merged in 2021-11, with the labels that each got.

#156 georgettica/bump go to 1.16
  Dockerfile
  go.mod
Labels: lgtm, approved

#154 update ocm-cli
  go.mod
  go.sum
Labels: lgtm, approved, tide/merge-method-squash

#155 OSD-8714 - Automate STS diff in osdctl
  README.md
  cmd/root.go
  cmd/sts/cmd.go
  cmd/sts/policy.go
  cmd/sts/policydiff.go
Labels: lgtm, approved

#152 make mockgen local
  Makefile
  go.mod
  go.sum
Labels: lgtm, approved, tide/merge-method-squash

#153 Modify UX/Output
  cmd/account/get/legal-entity.go
  cmd/account/mgmt/account-assign.go
  cmd/account/mgmt/account-list.go
  cmd/cost/get.go
  cmd/cost/list.go
  cmd/getoutput/getoutput.go
  cmd/root.go
Labels: approved

#137 Outputting info on stopped and running instances, updated cluster status to be a struct in the code.
  cmd/cluster/health.go
Labels: lgtm, approved

#157 feat(servicelog): post to custom list
  README.md
  cmd/servicelog/common.go
  cmd/servicelog/post.go
  internal/servicelog/clustersFile.go
Labels: lgtm, approved

#161 refactor unassign cmd
  cmd/account/list/account_test.go
  cmd/account/mgmt/account-unassign.go
  cmd/account/mgmt/account-unassign_test.go
  pkg/provider/aws/client.go
  pkg/provider/aws/mock/client.go
Labels: lgtm, approved
