Repository openshift/osdctl, pull requests merged in 2022-07, with the labels that each got.

#179 Ensure kubecli is set for packet-capture cmd
  cmd/network/packet-capture.go
Labels: lgtm, lifecycle/rotten, approved

#225 osd-11717 Onv command for osdctl
  README.md
  cmd/network/cmd.go
  cmd/network/verification.go
  go.mod
  go.sum
Labels: lgtm, approved, tide/merge-method-squash

#227 Added error checking, extracted token and connetion builders to use t…
  cmd/cluster/support/delete.go
  cmd/cluster/support/post.go
  cmd/cluster/support/status.go
  pkg/utils/utils.go
Labels: lgtm, approved, tide/merge-method-squash

#230 [OSD-12483]Adding SL output to cluster context command
  cmd/cluster/cmd.go
  cmd/cluster/context.go
  cmd/cluster/loggincheck.go
  cmd/servicelog/list.go
  internal/servicelog/reply.go
  pkg/utils/ocm.go
Labels: lgtm, approved

#187 Add support for internal service logs
  cmd/servicelog/list.go
  cmd/servicelog/post.go
Labels: lgtm, approved

#234 Fix URL usage for servicelog post templates
  cmd/servicelog/post.go
Labels: lgtm, approved

#233 OSD-11989 mock interface and refactors.
  cmd/cluster/support/delete.go
  cmd/cluster/support/post.go
  cmd/cluster/support/sdkmock.go
  cmd/cluster/support/status.go
  pkg/utils/utils.go
Labels: lgtm, approved

#235 Handle error from FetchServiceLogs properly
  cmd/servicelog/list.go
Labels: lgtm, approved
