Repository openshift/osdctl, pull requests merged in 2023-09, with the labels that each got.

#435 osd-network-verifier v0.4.2
  go.mod
  go.sum
Labels: lgtm, approved

#434 Add osdctl cluster resync command
  cmd/cluster/cmd.go
  cmd/cluster/resync.go
Labels: lgtm, approved

#439 Update `org context` so it doesn't return when failing to gather context
  cmd/org/context.go
Labels: lgtm, approved

#432 OSD-17941: Add etcd member replacement command
  cmd/cluster/cmd.go
  cmd/cluster/etcd_health.go
  cmd/cluster/etcd_replace.go
Labels: lgtm, approved, jira/valid-reference

#430 Update osdctl to go1.20.x
  .github/workflows/create_release.yml
  .github/workflows/validate_goreleaser.yml
  README.md
  go.mod
Labels: lgtm, approved

#441 pass customer-specified AWS tags to network verify-egress
  cmd/network/verification.go
  cmd/network/verification_test.go
Labels: lgtm, approved

#440 Refactors the PD service to be testable.
  cmd/cluster/context.go
  cmd/org/context.go
  go.mod
  go.sum
  pkg/provider/pagerduty/mocks/pagerduty_mock.go
  pkg/provider/pagerduty/pagerduty.go
  pkg/provider/pagerduty/pagerduty_suite_test.go
  pkg/provider/pagerduty/pagerduty_test.go
  pkg/utils/pagerduty.go
Labels: lgtm, approved, tide/merge-method-squash

#444 OSD-18416: Updated the docs with etcd health check and member replacement
  README.md
Labels: lgtm, approved, jira/valid-reference

#446 Get the port from the OCM info.
  cmd/cluster/hypershift_info.go
Labels: lgtm, approved
