Repository openshift/osdctl, pull requests merged in 2024-09, with the labels that each got.

#607 Bump osd-network-verifier-version to v1.0.1
  go.mod
  go.sum
Labels: lgtm, approved

#609 OSD-24259: osdctl network verify should prompt putting clusters into LS if DMS/PD is blocked
  cmd/network/verification.go
Labels: lgtm, approved, jira/valid-reference

#606 OCM-10376 | Add Limited Support Reason Override support
  cmd/cluster/support/status.go
  go.mod
  go.sum
Labels: lgtm, approved, ok-to-test

#610 Support Passing Namespace Ref For SaaS Promotions
  cmd/promote/git/app_interface.go
  cmd/promote/saas/saas.go
  cmd/promote/saas/utils.go
Labels: lgtm, approved

#611 Remove AlexVulaj from approvers
  OWNERS
Labels: lgtm, approved

#608 OSD-25183: Update Dynatrace related commands for osdctl
  cmd/cluster/context.go
  cmd/cluster/dynatrace/cluster.go
  cmd/cluster/dynatrace/hcpGatherLogsCmd.go
  cmd/cluster/dynatrace/logsCmd.go
  cmd/cluster/dynatrace/requests.go
  cmd/cluster/dynatrace/rootCmd.go
  cmd/cluster/dynatrace/urlCmd.go
  cmd/cluster/dynatrace/vault.go
  go.mod
  go.sum
  pkg/utils/ocm.go
Labels: lgtm, approved, tide/merge-method-squash, jira/valid-reference
