Repository openshift/osdctl, pull requests merged in 2024-03, with the labels that each got.

#530 Print version warnings to stderr
  cmd/cmd.go
Labels: lgtm, approved

#518 OSD-16848: Migrate ops-sop alert script as osdctl alert command
  cmd/alerts/cmd.go
  cmd/alerts/list_alerts.go
  cmd/alerts/silence/add_silence.go
  cmd/alerts/silence/clear_silence.go
  cmd/alerts/silence/cmd.go
  cmd/alerts/silence/common.go
  cmd/alerts/silence/list_silence.go
  cmd/cluster/etcd_health.go
  cmd/cmd.go
Labels: lgtm, approved, tide/merge-method-squash, ok-to-test, jira/valid-reference

#514 OSD-15091: Adding detachStuckVolume under cluster sub-command
  cmd/cluster/cmd.go
  cmd/cluster/detachstuckvolume.go
Labels: lgtm, approved, tide/merge-method-squash, jira/valid-reference

#535 Sort service logs by timestamp descending
  cmd/servicelog/common.go
  cmd/servicelog/list.go
Labels: lgtm, approved

#536 Adds JIRA Token Env var collection to reuse env var from CLI tool if set
  pkg/utils/jira.go
Labels: lgtm, approved

#533 Remove SL being sent when banned user is found
  cmd/cluster/checkbanneduser.go
Labels: lgtm, approved

#539 Add error message if running against cluster using isolated backplane flow
  cmd/cluster/cpd.go
Labels: lgtm, approved
