Repository openshift/osdctl, pull requests merged in 2024-07, with the labels that each got.

#590 Add myself & Tafhim to reviewers & approvers
  OWNERS
Labels: lgtm, approved

#591 OSD-24351: permission denied command should also evaluate read-only events
  cmd/cloudtrail/cloudtrail_test.go
  cmd/cloudtrail/permission-denied.go
  cmd/cloudtrail/pkg/aws/aws.go
  cmd/cloudtrail/write-events.go
Labels: lgtm, approved, jira/valid-reference

#589 OSD-23466 increase DT gather logs limit
  cmd/cluster/dynatrace/hcpGatherLogsCmd.go
  cmd/cluster/dynatrace/logsCmd.go
  cmd/cluster/dynatrace/requests.go
Labels: lgtm, approved, tide/merge-method-squash

#592 Don't use deprecated 'securityGroupId' in verifier library
  cmd/network/verification.go
  cmd/network/verification_test.go
Labels: lgtm, approved

#594 Prompt when putting critical customers into LS
  cmd/cluster/support/post.go
  pkg/utils/utils.go
Labels: lgtm, approved

#595 Remove missed use of deprecated SecurityGroupId in verifier test
  cmd/network/verification_test.go
Labels: lgtm, approved

#596 Update filter logic for finding subnets and security groups due to 4.16 changes
  cmd/network/verification.go
Labels: lgtm, approved, tide/merge-method-squash

#598 OSD-24614 : Update osdctl to add justification arguement for infranode resize
  cmd/cluster/resize/infra_node.go
Labels: lgtm, approved, tide/merge-method-squash

#588 OSD-20596: osdctl swarm secondary
  README.md
  cmd/cmd.go
  cmd/swarm/cmd.go
  cmd/swarm/secondary.go
Labels: lgtm, approved, tide/merge-method-squash, jira/valid-reference

#599 OSD-24621 - Add 'cluster ssh key' subcommand to find and print the ssh key for a cluster
  cmd/cluster/cmd.go
  cmd/cluster/ssh/key.go
  cmd/cluster/ssh/key_test.go
  cmd/cluster/ssh/ssh.go
  pkg/k8s/client.go
Labels: lgtm, approved

#597 [OSD-24377] Add new osdctl command to allow silencing alert(s) across a specific org
  cmd/alerts/silence/add_silence.go
  cmd/alerts/silence/cmd.go
  cmd/alerts/silence/silence_org.go
  cmd/org/clusters.go
  cmd/org/common.go
  cmd/org/context.go
Labels: lgtm, approved

#602 Add cpu arch flag to network verifier command
  cmd/network/verification.go
Labels: lgtm, approved
