Repository openshift/osdctl, pull requests merged in 2024-01, with the labels that each got.

#492 OSD-16588: Added Logic to Warn when Documentation does not matches Product type
  cmd/servicelog/post.go
Labels: lgtm, approved, jira/valid-reference

#496 adding servicelog check, interactive acceptance criteria, fixing inte…
  cmd/cluster/context.go
  cmd/org/context.go
  cmd/servicelog/common.go
  cmd/servicelog/post.go
  go.mod
Labels: lgtm, approved

#497 Remove unused flags and improve documentation around sts policy-diff
  cmd/sts/policydiff.go
Labels: lgtm, approved

#495 OSD-15383: osdctl LS delete without -i flag for single LS Reason
  cmd/cluster/support/delete.go
Labels: lgtm, approved, tide/merge-method-squash, jira/valid-reference

#501 OSD-20407: Fix osdctl cluster etcd related commands
  cmd/cluster/etcd_health.go
  cmd/cluster/etcd_replace.go
  cmd/cluster/transferowner.go
Labels: lgtm, approved, jira/valid-reference

#503 Minor UX refactor to cluster support post
  cmd/cluster/support/post.go
  cmd/cluster/support/post_test.go
Labels: lgtm, approved

#504 promote: Allow providing app-interface checkout directory
  cmd/promote/git/app_interface.go
  cmd/promote/git/git_cmd.go
  cmd/promote/pko/pko.go
  cmd/promote/saas/saas.go
  cmd/promote/saas/utils.go
Labels: lgtm, approved

#505 Update backplane-cli, osd-network-verifier
  .github/dependabot.yml
  go.mod
  go.sum
Labels: lgtm, approved
