Repository openshift/osdctl, pull requests merged in 2024-11, with the labels that each got.

#621 [OSD-19887]add replace pull secret for HCP clusters
  cmd/cluster/cleanup_leaked_ec2.go
  cmd/cluster/dynatrace/cluster.go
  cmd/cluster/transferowner.go
  cmd/network/verification.go
  go.mod
  go.sum
  pkg/utils/ocm.go
Labels: lgtm, approved

#623 OSD-26326: Replace GetHCPNamespace input field to support External ID
  cmd/cluster/context.go
  cmd/cluster/dynatrace/cluster.go
  cmd/cluster/dynatrace/logsCmd.go
Labels: lgtm, approved, tide/merge-method-squash, jira/valid-reference

#624 OSD-23467: Facilitate usage of osdctl dynatrace logs
  cmd/cluster/dynatrace/logsCmd.go
Labels: lgtm, approved, jira/valid-reference

#628 OSD-23467: Facilitate usage of osdctl dynatrace logs
  README.md
Labels: lgtm, approved, jira/valid-reference

#627 Update README.md to include setup command
  README.md
Labels: lgtm, approved

#618 Update osdctl cluster context to display LS override reason
  cmd/cluster/support/status.go
  pkg/utils/print.go
Labels: lgtm, approved

#629 OSD-25053: Refactor `osdctl network verify-egress` in anticipation of landing GCP support
  cmd/network/aws.go
  cmd/network/verification.go
  cmd/network/verification_test.go
Labels: lgtm, approved, jira/valid-reference

#633 [OSD-19887] change the update manifestwork logic to increamental
  cmd/cluster/transferowner.go
Labels: lgtm, approved

#630 OSD-25053: Add basic GCP support for network egress verification
  cmd/network/aws.go
  cmd/network/aws_test.go
  cmd/network/gcp.go
  cmd/network/gcp_test.go
  cmd/network/verification.go
  cmd/network/verification_test.go
  go.mod
Labels: lgtm, approved, jira/valid-reference

#635 Block running the network verifier for HCP clusters
  cmd/network/aws.go
Labels: lgtm, approved

#634 OSD-26539: Add commit sha and repository URL to the osdctl sre_operators commands
  cmd/cluster/sre_operators/describeCmd.go
  cmd/cluster/sre_operators/listCmd.go
Labels: lgtm, approved, jira/valid-reference

#636 Updates the readme release step
  README.md
Labels: lgtm, approved

#638 [bug] fix the hypershift detection
  cmd/cluster/transferowner.go
  pkg/utils/ocm.go
Labels: lgtm, approved
