Repository openshift/osdctl, pull requests merged in 2024-05, with the labels that each got.

#554 OSD-22501: Added some --egress-timeout option to 'osdctl network verify-egress' which is forwarded to osd-network-verifier
  cmd/network/verification.go
  cmd/network/verification_test.go
Labels: lgtm, approved, jira/valid-reference

#560 [SDE-3246] Cloudtail write-events feature
  cmd/cloudtrail/cmd.go
  cmd/cloudtrail/write-events.go
  cmd/cloudtrail/write-events_test.go
  cmd/cmd.go
  go.mod
  go.sum
  pkg/envConfig/config.go
Labels: lgtm, approved, tide/merge-method-squash

#555 [OSD-20552] - Gather Pod logs using DQL through OSDCTL
  cmd/cluster/dynatrace/cluster.go
  cmd/cluster/dynatrace/dtquery.go
  cmd/cluster/dynatrace/hcpGatherLogsCmd.go
  cmd/cluster/dynatrace/logsCmd.go
  cmd/cluster/dynatrace/requests.go
  cmd/cluster/dynatrace/rootCmd.go
  cmd/cluster/dynatrace/vault.go
Labels: lgtm, approved, tide/merge-method-squash

#561 Dynamically set OCM connection client from user config
  pkg/utils/ocm.go
Labels: lgtm, approved

#562 Add admin-username to rotate-secret command
  cmd/account/rotate-secret.go
Labels: lgtm, approved

#565 move control plane resize command under osdctl cluster resize
  cmd/cluster/cmd.go
  cmd/cluster/resize/cmd.go
  cmd/cluster/resize/controlplane_node.go
Labels: lgtm, approved

#567 Add --cpms flag to osdctl resize control-plane
  cmd/cluster/resize/controlplane_node.go
Labels: lgtm, approved

#568 ensure CPMS is active before attempting a resize
  cmd/cluster/resize/controlplane_node.go
Labels: lgtm, approved

#570 [OSD-22506] Add default region for STS GetCallerIdentity in rotate-creds
  cmd/account/rotate-secret.go
Labels: lgtm, approved

#571 Remove completion command
  cmd/cmd.go
  cmd/completion.go
Labels: lgtm, approved

#508 Added a check to "osdctl network verify-egress" for public subnets supplied by user with --subnet-id
  cmd/cluster/cpd.go
  cmd/network/verification.go
  cmd/network/verification_test.go
  go.mod
  go.sum
  pkg/utils/network.go
Labels: lgtm, approved

#576 Bump osd-network-verifier to version v0.4.11
  go.mod
  go.sum
Labels: lgtm, approved
