Repository openshift/osdctl, pull requests merged in 2024-04, with the labels that each got.

#543 Fix promote saas command for backplane-api
  cmd/promote/git/app_interface.go
Labels: lgtm, approved

#541 Osd 19190 - https://issues.redhat.com/browse/OSD-19190
  cmd/promote/git/service_repo.go
  cmd/promote/saas/utils.go
Labels: lgtm, approved

#532 OSD-20509: Updates infra resize command to add SL for GCP
  cmd/cluster/resize/infra_node.go
Labels: lgtm, approved, tide/merge-method-squash, jira/valid-reference

#544 Osd 19190 - https://issues.redhat.com/browse/OSD-19190 - criteria 3
  cmd/promote/saas/saas.go
Labels: lgtm, approved

#540 [OSD-20175] - DQL in OSDCTL
  cmd/cluster/cmd.go
  cmd/cluster/context.go
  cmd/cluster/dynatrace/cluster.go
  cmd/cluster/dynatrace/dtquery.go
  cmd/cluster/dynatrace/logsCmd.go
  cmd/cluster/dynatrace/requests.go
  cmd/cluster/dynatrace/rootCmd.go
  cmd/cluster/dynatrace/urlCmd.go
  cmd/cluster/dynatrace/vault.go
Labels: lgtm, approved

#547 Bump osd-network-verifier to v0.4.8
  go.mod
  go.sum
Labels: lgtm, approved

#548 OSD-20175: Minor fixes to dynatrace logs commands
  cmd/cluster/dynatrace/logsCmd.go
  cmd/cluster/dynatrace/requests.go
  cmd/cluster/dynatrace/vault.go
Labels: lgtm, approved, jira/valid-reference

#549 OSD-22368: Using the KMS key defined for the cluster instead of 'aws/ebs' when calling osd-network-verifier
  cmd/network/verification.go
  cmd/network/verification_test.go
Labels: lgtm, approved, jira/valid-reference

#550 avoid nil exception when awsMachine do not have InstanceIds
  cmd/cluster/cleanup_leaked_ec2.go
Labels: lgtm, approved

#551 Improve messaging around cluster uninstallation expectations
  cmd/cluster/cleanup_leaked_ec2.go
Labels: lgtm, approved

#553 terminate only running and stopped instances when cleaning up leaked ec2
  cmd/cluster/cleanup_leaked_ec2.go
Labels: lgtm, approved, tide/merge-method-squash

#534 OSD-19982: osdctl improve limited support workflow
  cmd/cluster/support/common.go
  cmd/cluster/support/post.go
Labels: lgtm, approved, tide/merge-method-squash, jira/valid-reference

#556 Update network verifier to v0.4.9
  go.mod
  go.sum
Labels: lgtm, approved

#558 [OSD-22777]Update ami lookup filter for jumphost creation
  cmd/jumphost/create.go
Labels: lgtm, approved
