Repository openshift/osdctl, pull requests merged in 2024-06, with the labels that each got.

#578 OSD-23744: make context cmd quicker
  cmd/cluster/context.go
  go.mod
  pkg/utils/delay_tracker.go
  pkg/utils/ocm.go
  pkg/utils/ocm_test.go
  pkg/utils/print.go
Labels: lgtm, approved, tide/merge-method-squash, jira/valid-reference

#582 Add version flag to verify egress command for osd-network-verifier version
  cmd/network/verification.go
  pkg/utils/utils.go
  pkg/utils/utils_test.go
Labels: lgtm, approved

#585 OSD-22635: use elevation for oc execs
  cmd/alerts/list_alerts.go
  cmd/alerts/silence/add_silence.go
  cmd/alerts/silence/clear_silence.go
  cmd/alerts/silence/common.go
  cmd/alerts/silence/list_silence.go
  cmd/cluster/detachstuckvolume.go
Labels: lgtm, approved, jira/valid-reference

#587 Removes requirement that '--problem' strings cannot end in punctuation
  cmd/cluster/support/post.go
Labels: lgtm, approved

#575 [OSD-23212] Cloudtrailmcmd Permission-denied history Feature
  cmd/cloudtrail/cloudtrail_test.go
  cmd/cloudtrail/cmd.go
  cmd/cloudtrail/permission-denied.go
  cmd/cloudtrail/pkg/aws/aws.go
  cmd/cloudtrail/pkg/util.go
  cmd/cloudtrail/write-events.go
  cmd/cloudtrail/write-events_test.go
Labels: lgtm, approved, tide/merge-method-squash

#545 [OSD-22074] Bug Fix for osdctl alerts silence add fails to run pod
  cmd/alerts/silence/add_silence.go
  cmd/alerts/silence/common.go
Labels: lgtm, approved

#583 [OSD-22253] refactor sts command to support wif as well
  cmd/cmd.go
  cmd/iampermissions/cmd.go
  cmd/iampermissions/diff.go
  cmd/iampermissions/get.go
  cmd/iampermissions/save.go
  cmd/sts/cmd.go
  cmd/sts/policy.go
  cmd/sts/policydiff.go
  go.mod
  go.sum
  pkg/policies/aws.go
  pkg/policies/cloudspec.go
  pkg/policies/gcp.go
  pkg/policies/gcp_models.go
  pkg/policies/policy.go
Labels: lgtm, approved

#580 OSD-22394 osdctl alert silence --all does not silence
  cmd/alerts/list_alerts.go
  cmd/alerts/silence/add_silence.go
  cmd/alerts/silence/clear_silence.go
  cmd/alerts/silence/list_silence.go
  cmd/alerts/utils/alert.go
  cmd/alerts/utils/silence.go
  cmd/alerts/utils/utils.go
Labels: lgtm, approved

#581 OSD-23280 Osdctl configuration setup
  cmd/cmd.go
  cmd/setup/setup.go
  cmd/setup/setup_test.go
Labels: lgtm, approved
