Repository openshift/osdctl, pull requests merged in 2025-09, with the labels that each got.

#791 SREP-1191: add SDN-to-OVN migration check to osdctl cluster context
  cmd/cluster/context.go
  cmd/cluster/context_test.go
  pkg/utils/utils.go
Labels: lgtm, approved, jira/valid-reference

#779 Add a RPM spec file
  .github/workflows/trigger_copr.yaml
  README.md
  hack/copr.sh
  hack/osdctl.spec
Labels: lgtm, approved

#796 Fix formatting of commit message for dynatrace promotions
  cmd/promote/dynatrace/dt_utils.go
  cmd/promote/dynatrace/dynatrace.go
Labels: lgtm, approved

#798 Adds helper info to `promotion` commit error message; prints commit message
  cmd/promote/dynatrace/dt_utils.go
  cmd/promote/saas/utils.go
Labels: lgtm, approved

#795 SREP-966: reimplement pull-secret email validation without backplane elevation
  cmd/cluster/validatepullsecret.go
  docs/README.md
  docs/osdctl_cluster_validate-pull-secret.md
  go.mod
  pkg/backplane/client.go
  pkg/backplane/client_test.go
Labels: lgtm, approved, tide/merge-method-squash, jira/valid-reference

#799 servicelog post should support read query from file as clusters input
  cmd/servicelog/post.go
  cmd/servicelog/post_test.go
Labels: lgtm, approved

#803 Remove fahlmant from OWNERS
  OWNERS
Labels: lgtm, approved
