Repository openshift/osdctl, pull requests merged in 2025-05, with the labels that each got.

#732 OSD-29210 - only allow supported instance types when running osdctl cluster resize X
  cmd/cluster/resize/cmd.go
  cmd/cluster/resize/controlplane_node.go
  cmd/cluster/resize/infra_node.go
  cmd/cluster/resize/infra_node_test.go
Labels: lgtm, approved, tide/merge-method-squash

#738 Added test cases of aws.go and util.go file under pkg under cloudtrail
  cmd/cloudtrail/pkg/aws/aws_test.go
  cmd/cloudtrail/pkg/aws/testdata/valid_event.json
  cmd/cloudtrail/pkg/util_test.go
Labels: lgtm, approved, tide/merge-method-squash

#723 OSD-29084: Tc pkg pko and git
  cmd/promote/git/app_interface.go
  cmd/promote/git/app_interface_test.go
  cmd/promote/git/git_cmd.go
  cmd/promote/git/service_repo.go
  cmd/promote/iexec/iexec.go
  cmd/promote/pko/pko.go
  cmd/promote/saas/saas.go
  cmd/promote/saas/utils.go
Labels: lgtm, approved, tide/merge-method-squash, ok-to-test, jira/valid-reference

#742 OSD-29210: Add gcp instance types to cluster resize command
  cmd/cluster/resize/cmd.go
  cmd/cluster/resize/infra_node.go
Labels: lgtm, approved, jira/valid-reference

#728 OSD-29161: Added test cases for support package
  cmd/cluster/support/delete_test.go
  cmd/cluster/support/post_test.go
Labels: lgtm, approved, tide/merge-method-squash, jira/valid-reference

#743 Ensure Go 1.23 Everywhere + Fix CVEs
  .ci-operator.yaml
  Dockerfile
  Makefile
  go.mod
  go.sum
Labels: lgtm, approved, tide/merge-method-squash

#740 OSD-28497: Fixes to allow `osdctl account rotate-secret` to work with `rh-aws-saml-login`.
  cmd/account/rotate-secret.go
  cmd/account/rotate-secret_test.go
Labels: lgtm, approved, jira/valid-reference

#720 OSD-29082: Test cases for dynatrace and saas for promote
  cmd/promote/dynatrace/dt_app_interface.go
  cmd/promote/dynatrace/dt_app_interface_test.go
  cmd/promote/dynatrace/dt_git_cmd.go
  cmd/promote/dynatrace/dt_git_cmd_test.go
  cmd/promote/dynatrace/dt_service_repo.go
  cmd/promote/dynatrace/dt_service_repo_test.go
  cmd/promote/dynatrace/dt_utils.go
  cmd/promote/dynatrace/dynatrace.go
  cmd/promote/dynatrace/dynatrace_config.go
  cmd/promote/dynatrace/dynatrace_config_test.go
  cmd/promote/dynatrace/tf_file_update_test.go
  cmd/promote/dynatrace/utils_test.go
  cmd/promote/saas/utils_test.go
Labels: lgtm, approved, ok-to-test, jira/valid-reference

#746 Fix `osdctl cluster resize` support when not passing an instance type
  cmd/cluster/resize/infra_node.go
Labels: lgtm, approved

#748 Fix the linting config and a selection of failures
  .gitignore
  .golangci.yaml
  Makefile
  cmd/account/mgmt/account-assign.go
  cmd/account/rotate-secret.go
  cmd/cloudtrail/cmd.go
  cmd/cloudtrail/permission-denied.go
  cmd/cloudtrail/write-events.go
  cmd/cluster/access/cleanup.go
  cmd/cluster/checkbanneduser.go
  cmd/cluster/context.go
  cmd/cluster/etcd_replace.go
  cmd/cluster/hypershift_info.go
  cmd/cluster/resize/controlplane_node.go
  cmd/cluster/ssh/key.go
  cmd/cluster/support/delete.go
  cmd/cluster/support/status.go
  cmd/cost/list_test.go
  cmd/dynatrace/hcpGatherLogsCmd.go
  cmd/dynatrace/urlCmd.go
  cmd/env/env.go
  cmd/hcp/mustgather/mustGather.go
  cmd/hcp/mustgather/mustGather_test.go
  cmd/iampermissions/diff.go
  cmd/iampermissions/get.go
  cmd/iampermissions/save.go
  cmd/jumphost/create.go
  cmd/jumphost/create_test.go
  cmd/jumphost/delete.go
  cmd/mc/list.go
  cmd/org/aws-accounts.go
  cmd/org/clusters.go
  cmd/org/common.go
  cmd/org/customers_test.go
  cmd/org/describe_test.go
  cmd/org/get_test.go
  cmd/promote/dynatrace/dt_app_interface.go
  cmd/promote/dynatrace/tf_file_update.go
  cmd/promote/dynatrace/tf_file_update_test.go
  cmd/promote/git/app_interface.go
  cmd/promote/git/app_interface_test.go
  cmd/promote/saas/saas.go
  cmd/servicelog/post_test.go
  cmd/setup/setup.go
  internal/utils/file.go
  pkg/docgen/docgen.go
  pkg/envConfig/config.go
  pkg/osdCloud/aws.go
  pkg/osdCloud/gcp.go
  pkg/osdctlConfig/osdctlConfig.go
  pkg/provider/pagerduty/pagerduty.go
Labels: lgtm, approved

#747 OSD-29994: Improve sre-operators command misleading message
  cmd/cluster/sre_operators/describeCmd.go
  cmd/cluster/sre_operators/listCmd.go
  go.mod
  go.sum
Labels: lgtm, approved, jira/valid-reference

#750 OSD-30081: Fix issues with `osdctl promote saas`
  cmd/promote/git/app_interface.go
  cmd/promote/git/git_cmd.go
  cmd/promote/git/service_repo.go
  cmd/promote/pko/pko.go
  cmd/promote/saas/saas.go
Labels: lgtm, approved, jira/valid-reference

#751 SREP-325: Use our `boilerplate` base image in CI
  .ci-operator.yaml
Labels: lgtm, approved, jira/valid-reference

#736 OSD-29158: Added test cases for cluster package
  cmd/cluster/etcd_health_test.go
  cmd/cluster/etcd_replace_test.go
  cmd/cluster/transferowner_test.go
Labels: lgtm, approved, tide/merge-method-squash, jira/valid-reference

#755 Adds region-aware Splunk URL building
  cmd/cluster/context.go
  cmd/cluster/context_test.go
  pkg/utils/ocm.go
Labels: lgtm, approved

#756 OSD-29082: bug fix
  cmd/promote/dynatrace/dt_app_interface.go
  cmd/promote/dynatrace/dt_service_repo.go
Labels: lgtm, needs-ok-to-test, approved, jira/valid-reference

#757 Fix: promote saas-osd-rhobs-rules-and-dashboards
  cmd/promote/git/app_interface.go
Labels: lgtm, approved

#754 OSD-21668 - Automate manual steps on the cluster ownership transfer process
  cmd/cluster/transferowner.go
  docs/README.md
  docs/osdctl_cluster_transfer-owner.md
Labels: lgtm, approved, tide/merge-method-squash

#749 Restarted/Cycled pod logs by namespace in DT gather-logs
  cmd/dynatrace/hcpGatherLogsCmd.go
Labels: lgtm, approved, tide/merge-method-squash
