Repository openshift/osdctl, pull requests merged in 2025-07, with the labels that each got.

#772 SREP-1010: Added "osdctl dt" check for vault cli
  cmd/dynatrace/vault.go
Labels: lgtm, approved, tide/merge-method-squash, jira/valid-reference

#774 Add SRE-P Orange to owners
  OWNERS
Labels: lgtm, approved

#771 Update HCP Must-Gather help
  cmd/hcp/mustgather/mustGather.go
  docs/osdctl_hcp_must-gather.md
Labels: lgtm, approved

#775 Replace unmaintained pkg golang-gomock with uber-gomock
  go.mod
  go.sum
  pkg/utils/jira_test.go
  pkg/utils/mocks/jira_mock.go
Labels: lgtm, approved

#773 SREP-1005: fix osdctl dt logs console URL
  cmd/dynatrace/logsCmd.go
Labels: lgtm, approved, jira/valid-reference

#778 SREP-1062 Adding network info section to cluster context
  cmd/cluster/context.go
Labels: lgtm, approved

#780 SREP-962: Add absolute timestamp support to fetching DT logs (--from and --to flags)
  cmd/cluster/context.go
  cmd/dynatrace/dtquery.go
  cmd/dynatrace/dtquery_test.go
  cmd/dynatrace/logsCmd.go
  docs/README.md
  docs/osdctl_dynatrace_logs.md
  go.mod
  go.sum
Labels: lgtm, approved, jira/valid-reference

#781 Standardize --cluster-id flag to support -C shorthand across all commands
  cmd/alerts/list_alerts.go
  cmd/alerts/silence/add_silence.go
  cmd/alerts/silence/clear_silence.go
  cmd/alerts/silence/list_silence.go
  cmd/cluster/access/access.go
  cmd/cluster/access/cleanup.go
  cmd/cluster/checkbanneduser.go
  cmd/cluster/context.go
  cmd/cluster/detachstuckvolume.go
  cmd/cluster/etcd_health.go
  cmd/cluster/etcd_replace.go
  cmd/cluster/hypershift_info.go
  cmd/cluster/loggingcheck.go
  cmd/cluster/org_id.go
  cmd/cluster/resize/controlplane_node.go
  cmd/cluster/ssh/key.go
  cmd/cluster/support/delete.go
  cmd/cluster/support/post.go
  cmd/cluster/support/status.go
  cmd/cluster/validatepullsecret.go
  cmd/dynatrace/dashCmd.go
  cmd/dynatrace/hcpGatherLogsCmd.go
  cmd/dynatrace/logsCmd.go
  cmd/dynatrace/urlCmd.go
  cmd/env/env.go
  cmd/hcp/mustgather/mustGather.go
  docs/README.md
  docs/osdctl_alert_list.md
  docs/osdctl_alert_silence_add.md
  docs/osdctl_alert_silence_expire.md
  docs/osdctl_alert_silence_list.md
  docs/osdctl_cluster_break-glass.md
  docs/osdctl_cluster_break-glass_cleanup.md
  docs/osdctl_cluster_check-banned-user.md
  docs/osdctl_cluster_context.md
  docs/osdctl_cluster_detach-stuck-volume.md
  docs/osdctl_cluster_etcd-health-check.md
  docs/osdctl_cluster_etcd-member-replace.md
  docs/osdctl_cluster_hypershift-info.md
  docs/osdctl_cluster_logging-check.md
  docs/osdctl_cluster_orgId.md
  docs/osdctl_cluster_resize_control-plane.md
  docs/osdctl_cluster_ssh_key.md
  docs/osdctl_cluster_support_delete.md
  docs/osdctl_cluster_support_post.md
  docs/osdctl_cluster_support_status.md
  docs/osdctl_cluster_validate-pull-secret.md
  docs/osdctl_dynatrace_dashboard.md
  docs/osdctl_dynatrace_gather-logs.md
  docs/osdctl_dynatrace_logs.md
  docs/osdctl_dynatrace_url.md
  docs/osdctl_env.md
  docs/osdctl_hcp_must-gather.md
Labels: lgtm, approved
