Repository openshift/osdctl, pull requests merged in 2025-02, with the labels that each got.

#658 SDCICD-1418 add cmd option to promote operator saas through canary hives
  cmd/promote/git/app_interface.go
  cmd/promote/saas/saas.go
  cmd/promote/saas/utils.go
  go.mod
  go.sum
Labels: lgtm, approved

#660 Feat(OSD-25864): add osdctl hcp must-gather
  cmd/cluster/cleanup_leaked_ec2.go
  cmd/cluster/cleanup_leaked_ec2_test.go
  cmd/cluster/cmd.go
  cmd/cmd.go
  cmd/dynatrace/hcpGatherLogsCmd.go
  cmd/hcp/cmd.go
  cmd/hcp/mustgather/mustGather.go
  cmd/hcp/mustgather/mustGather_test.go
  go.mod
  go.sum
  pkg/k8s/account_test.go
Labels: lgtm, approved

#662 Cleanup defunct comment
  cmd/promote/git/app_interface.go
Labels: lgtm, approved

#666 Maint: remove dependency on "oc" for the osdctl hcp must-gather command
  cmd/hcp/mustgather/mustGather.go
  go.mod
  go.sum
Labels: lgtm, approved

#670 Feat(OSD-25864): update osdctl hcp must-gather to create hypershift dumps
  cmd/hcp/mustgather/mustGather.go
Labels: lgtm, approved, tide/merge-method-squash

#671 OSD-24997: Show if a user is banned when using osdctl cluster context
  cmd/cluster/context.go
Labels: lgtm, approved, jira/valid-reference

#672 OSD-24628 - added external id to osdctl org clusters
  cmd/org/clusters.go
Labels: lgtm, approved
