Repository openshift/osdctl, pull requests merged in 2025-04, with the labels that each got.

#711 OSD-28837 Update osdctl to send a SL instead of LS when cluster "not ready"
  cmd/network/verification.go
Labels: lgtm, approved

#712 [OSD-28483] Add an `osdctl dt dash` command
  cmd/dynatrace/cluster.go
  cmd/dynatrace/dashCmd.go
  cmd/dynatrace/hcpGatherLogsCmd.go
  cmd/dynatrace/logsCmd.go
  cmd/dynatrace/requests.go
  cmd/dynatrace/rootCmd.go
Labels: lgtm, approved

#715 Bump goreleaser to v2
  .goreleaser.yml
  Makefile
Labels: lgtm, approved

#716 Bump osd-network-verifier to v1.2.3
  go.mod
  go.sum
Labels: lgtm, approved

#697 OSD-28325: Added test cases for access.go
  cmd/cluster/access/access_test.go
Labels: lgtm, approved, tide/merge-method-squash, jira/valid-reference

#719 SDCICD-1418 show inscope rollout link in promotion PR description
  cmd/promote/saas/utils.go
Labels: lgtm, approved, tide/merge-method-squash

#699 Osd 28496 pkg jumphost
  cmd/jumphost/cmd_test.go
  cmd/jumphost/create.go
  cmd/jumphost/create_test.go
Labels: lgtm, approved

#710 OSD-28715 Added unit test case for Common file under Servicelog Pkg
  cmd/servicelog/common_test.go
Labels: lgtm, approved

#727 Fix panic and other misc code issues for 'osdctl cluster support post'
  cmd/cluster/support/cmd.go
  cmd/cluster/support/post.go
Labels: lgtm, approved

#695 OSD-28400: Added test cases for clustersync.go
  cmd/hive/clustersync.go
  cmd/hive/clustersync_test.go
Labels: lgtm, approved, tide/merge-method-squash, jira/valid-reference

#731 Fix verify docs
  docs/README.md
  docs/osdctl_cluster_support_post.md
  docs/osdctl_iampermissions.md
  docs/osdctl_iampermissions_diff.md
  scripts/verify-docs.sh
Labels: lgtm, approved

#733 Updating SL template URLs to RAW urls in github
  cmd/cluster/transferowner.go
Labels: lgtm, approved

#734 OSD-29167: Testcases pkg account
  cmd/account/console_test.go
  cmd/account/generate-secret_test.go
  cmd/account/rotate-secret_test.go
Labels: lgtm, needs-ok-to-test, approved, jira/valid-reference

#737 [OSD-29837] Use v2 `sre-capabilities` label to find DT tenant info
  pkg/utils/ocm.go
Labels: lgtm, approved

#706 OSD-28399 : Added unit test case for context and cluster under org pkg
  cmd/org/clusters.go
  cmd/org/clusters_test.go
  cmd/org/context.go
  cmd/org/context_test.go
  cmd/org/testdata/jsonClusters.txt
  cmd/org/testdata/tableClusters.txt
  docs/README.md
  docs/osdctl_org_clusters.md
  docs/osdctl_org_context.md
Labels: lgtm, approved, tide/merge-method-squash
