Repository openshift/osdctl, pull requests merged in 2025-03, with the labels that each got.

#668 OSD-27873-dynatrace-component-promotion
  cmd/promote/cmd.go
  cmd/promote/dynatrace/dt_app_interface.go
  cmd/promote/dynatrace/dt_git_cmd.go
  cmd/promote/dynatrace/dt_service_repo.go
  cmd/promote/dynatrace/dt_utils.go
  cmd/promote/dynatrace/dynatrace.go
Labels: lgtm, approved

#681 OSD-21613 - Support isolated backplane flow for 'osdctl cluster cpd' command
  cmd/cluster/cpd.go
Labels: lgtm, approved

#686 added unit tests for setup.go
  cmd/setup/setup_test.go
  go.mod
Labels: lgtm, approved, tide/merge-method-squash

#689 Remove unused --cluster-id flag from context command
  cmd/cluster/context.go
Labels: lgtm, approved

#691 Remove legacy controlplane resize command
  cmd/cluster/resize/controlplane_node.go
Labels: lgtm, approved

#687 OSD-28274 Dynatrace Config terraform promotion
  cmd/promote/dynatrace/dt_utils.go
  cmd/promote/dynatrace/dynatrace.go
  cmd/promote/dynatrace/dynatrace_config.go
  cmd/promote/dynatrace/dynatrace_suite_test.go
  cmd/promote/dynatrace/tf_file_update.go
  cmd/promote/dynatrace/tf_file_update_test.go
  cmd/promote/dynatrace/utils_test.go
  go.mod
  go.sum
Labels: lgtm, approved

#678 Osd 22527: osdctl "jiratoken" flag in "cluster context" command is not used
  cmd/cluster/context.go
  cmd/jira/quick-task.go
  cmd/org/context.go
  cmd/swarm/secondary.go
  pkg/utils/jira.go
Labels: lgtm, approved, tide/merge-method-squash

#690 Osd 24440: Elevate oc cp command
  cmd/network/packet-capture.go
Labels: lgtm, approved, tide/merge-method-squash

#698 OSD-28828 : Fixed osdctl promote dynatrace command
  cmd/promote/dynatrace/dt_app_interface.go
Labels: lgtm, approved

#676 Test Cases for context.go
  cmd/cluster/context.go
  cmd/cluster/context_test.go
Labels: lgtm, approved

#677 implemented test cases for network package
  cmd/network/packet-capture_test.go
  cmd/network/verification_test.go
  go.mod
  pkg/k8s/client.go
Labels: lgtm, approved, tide/merge-method-squash

#692 Added unit test case for current and customer file under org package
  cmd/org/current.go
  cmd/org/current_test.go
  cmd/org/customers.go
  cmd/org/customers_test.go
  go.mod
  go.sum
Labels: lgtm, approved, tide/merge-method-squash

#682 Allow any type of cluster ID when initializing backplane access
  cmd/common/helpers.go
Labels: lgtm, approved

#707 OSD: 27238 - osdctl controlplane resize should not wait for completion
  cmd/cluster/resize/controlplane_node.go
Labels: lgtm, approved, tide/merge-method-squash

#696 Add unit tests for servicelog in post_test.go
  cmd/servicelog/post_test.go
Labels: lgtm, approved

#708 OSD-28146 added FedRAMP STAGE and INT envs to ocm.go
  pkg/utils/ocm.go
Labels: lgtm, approved

#702 OSD-28215: Add new cmd for extended pull secret validations
  cmd/cluster/cmd.go
  cmd/cluster/validatepullsecretext.go
  cmd/cluster/validatepullsecretext_test.go
Labels: lgtm, approved, jira/valid-reference
