Repository openshift/osdctl, pull requests merged in 2025-08, with the labels that each got.

#786 Use boilerplate v8 in CI
  .ci-operator.yaml
Labels: lgtm, approved

#784 SREP-862: Add support for `osdctl network verify-egress --pod-mode`
  cmd/network/verification.go
  cmd/network/verification_pod_mode_test.go
  docs/README.md
  docs/osdctl_network_verify-egress.md
  go.mod
  go.sum
  pkg/k8s/client.go
Labels: kind/feature, lgtm, approved, tide/merge-method-squash, jira/valid-reference

#792 SREP-949: osdctl should be extended to allow quickly and easily pushing a hotfix version to the fleet for a given codebase
  cmd/promote/git/app_interface.go
  cmd/promote/git/app_interface_test.go
  cmd/promote/saas/saas.go
  cmd/promote/saas/utils.go
  cmd/promote/saas/utils_test.go
  docs/README.md
  docs/osdctl_promote_saas.md
Labels: lgtm, approved, tide/merge-method-squash, jira/valid-reference
